CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_progress (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  high_score INT DEFAULT 0,
  turns INT DEFAULT 0,
  time_taken INT DEFAULT 0,
  hints_used INT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
